import { BALANCE as B, TROLL_UPGRADE_BRANCHES, trollBranchPoints, trollCost, trollUpgradeStatus } from '../shared/config.js';
import { ITEMS, EQUIPMENT_SLOTS, BUILDS, upgradePreview } from '../shared/equipment.js';
import { icon } from './icons.js';
import { resource } from './resources.js';

export function shopMarkup(u,time,tab='gear',build='siege'){
  const equipped=Object.values(u.equipment||{}),recommended=BUILDS[build],totalLevels=Object.values(u.levels||{}).reduce((sum,level)=>sum+level,0),legendary=(u.levels.damage||0)+(u.levels.siege||0)>=B.legendary.swordLevels&&totalLevels>=B.legendary.swordTotalLevels;
  const busy=time-u.lastHit<5||(u.lastAttack>0&&time-u.lastAttack<5)||(u.cooldowns.attack||0)>time;
  const header=`<button class="modal-close" data-do="shop" aria-label="Fechar loja">${icon('close')} <kbd>G</kbd></button><div class="eyebrow">ARSENAL DO BOSQUE</div><h2>Arsenal <span>${resource('gold',u.gold)}</span></h2><p class="keyboard-note"><kbd>WASD</kbd>/<kbd>↑↓</kbd> navegar · <kbd>Enter</kbd> confirmar · <kbd>G</kbd> fechar</p><div class="shop-tabs" role="tablist" aria-label="Loja do Troll"><button role="tab" aria-selected="${tab==='gear'}" data-do="shop-tab" data-tab="gear">Equipamentos</button><button role="tab" aria-selected="${tab==='levels'}" data-do="shop-tab" data-tab="levels">Árvore de crescimento</button></div>`;
  if(tab==='levels')return header+`<p>${legendary?'⚔ ESPADA LENDÁRIA ATIVA · golpes executam estruturas abaixo de 15% HP.':`Espada Lendária: Fúria + Quebra-fortaleza ${u.levels.damage+u.levels.siege}/${B.legendary.swordLevels} · níveis totais ${totalLevels}/${B.legendary.swordTotalLevels}.`}</p><div class="growth-tree">${Object.entries(TROLL_UPGRADE_BRANCHES).map(([branchId,branch])=>`<section class="growth-branch branch-${branchId}"><header><span>${branch.name}</span><small>${trollBranchPoints(u.levels,branchId)} pontos · ${branch.description}</small></header><div class="attribute-grid">${branch.keys.map(key=>{
    const d=B.upgrades[key],level=u.levels[key],cost=trollCost(key,level),status=trollUpgradeStatus(u.levels,key),capped=status.code==='max';
    return `<button class="shop-item" data-do="buy" data-key="${key}" title="${d.description}" ${!status.allowed||u.gold<cost?'disabled':''}><span><b>${d.name} <small>${capped?`Nv. ${level} · ÉPICO`:`Nv. ${level} → ${level+1} · ${status.band.name}`}</small></b><small>${capped?'Nível máximo':upgradePreview(u,key)}</small></span><strong>${capped?'MAX':resource('gold',cost)}</strong></button>`;
  }).join('')}</div></section>`).join('')}</div><p class="shop-note">Os ramos organizam estilos de jogo sem impedir combinações. Níveis 11–15 são Lendários; 16–20 são Épicos.</p>`;
  return header+`<div class="build-choices" aria-label="Sugestões de build">${Object.entries(BUILDS).map(([id,b])=>`<button data-do="shop-build" data-build="${id}" aria-pressed="${id===build}">${b.name}</button>`).join('')}</div><p class="build-description">${recommended.description}</p><div class="equipment-grid">${Object.entries(EQUIPMENT_SLOTS).map(([slot,label])=>`<section><h3>${label}<small>${ITEMS[u.equipment[slot]]?.name||'Espaço livre'}</small></h3>${Object.entries(ITEMS).filter(([,item])=>item.slot===slot).map(([id,item])=>{
    const owned=u.inventory.includes(id),active=equipped.includes(id),suggested=recommended.items.includes(id);
    return `<article class="item-card ${active?'equipped':''} ${suggested?'recommended':''}"><div class="item-title"><div class="item-art item-${id}">${icon({maul:'heavy',claws:'sword',edge:'sword',carapace:'armor',mantle:'dash',moss:'leaf',totem:'roar',hunt:'target',amber:'relic'}[id])}</div><b>${item.name}</b>${suggested?'<span title="Faz parte da build selecionada">◆</span>':''}</div><p>${item.description}</p><button data-do="${owned?'equip-item':'buy-item'}" data-item="${id}" ${active||busy||(!owned&&u.gold<item.cost)?'disabled':''}>${active?'✓ Equipado':owned?'Equipar':`${resource('gold',item.cost)} · Comprar`}</button></article>`;
  }).join('')}</section>`).join('')}</div><p class="shop-note">${busy?'Em combate · aguarde 5s sem causar ou receber dano.':'3 espaços · misture as builds. Itens comprados ficam na coleção.'}</p>`;
}
