import { randomUUID } from 'node:crypto';
import { RANK_CONFIG, rankProgress, tierForRating } from '../shared/rank-config.js';
import { RankingEngine } from './ranking.js';

const parse=value=>{try{return JSON.parse(value);}catch{return {};}};
const positiveInt=(value,fallback,max=100)=>Math.min(max,Math.max(1,Number.parseInt(value,10)||fallback));
const botMetadata=occupant=>{const name=occupant.name||'Bot',slug=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'');return {botId:occupant.botId||`BOT_${occupant.role?.toUpperCase()||'PLAYER'}_${slug}_${occupant.difficulty?.toUpperCase()||'NORMAL'}_V1`,strategy:occupant.strategy||slug.toLowerCase(),version:occupant.version||'v1'};};

export class PlatformService{
  constructor(database,{simulationEnabled=process.env.RANKED_SIMULATION_ENABLED!=='false',devMode=false,log=console.log}={}){this.database=database;this.db=database.db;this.simulationEnabled=simulationEnabled;this.devMode=devMode;this.ranking=new RankingEngine(database,{log});this.log=log;}
  classify(room){const humans=room.slots.filter(slot=>slot.occupant?.type==='human').length,bots=room.slots.filter(slot=>slot.occupant?.type==='bot').length;if(this.devMode&&room.settings.local)return 'developer';if(room.settings.mode==='custom')return 'custom';if(!humans&&bots)return 'bots';return humans>1?'pvp':'bots';}
  rankedStatus(room){if(room.settings.mode==='ranked')return 'ranked';return this.simulationEnabled?'simulated_ranked':'unranked';}
  participantIdentities(room){return room.slots.filter(slot=>slot.occupant).map(slot=>{const occupant=slot.occupant;if(occupant.userId){return {unitId:slot.id,playerId:'user:'+occupant.userId,userId:occupant.userId,displayName:occupant.name,type:'human',role:slot.role};}if(occupant.type==='human'){return {unitId:slot.id,playerId:'guest:'+occupant.clientId,displayName:occupant.name,type:'guest',role:slot.role};}const bot=botMetadata({...occupant,role:slot.role});return {unitId:slot.id,playerId:'bot:'+bot.botId,displayName:occupant.name,type:'bot',role:slot.role,...bot};}).filter(Boolean);}
  recordMatch(room,result){
    if(!result.completed)return {persisted:false,reason:'not-completed'};const externalId=room.platformMatchId||`${room.id}:${room.matchSequence}:${room.created}`,existing=this.db.prepare('SELECT id,rank_processing_status FROM matches WHERE external_id=?').get(externalId);if(existing)return {persisted:false,idempotent:true,matchId:existing.id};
    const id=randomUUID(),seasonId=RANK_CONFIG.seasonId,matchType=this.classify(room),rankedStatus=this.rankedStatus(room),timestamp=new Date().toISOString(),participants=this.participantIdentities(room),release=typeof result.release==='string'?result.release:result.release?JSON.stringify(result.release):null;
    try{return this.database.transaction(()=>{
      this.db.prepare('INSERT INTO matches(id,external_id,season_id,match_type,ranked_status,mode,seed,winner,duration,completed,end_reason,release,build_hash,result_json,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,externalId,seasonId,matchType,rankedStatus,room.settings.mode,result.seed,result.winner,result.duration,1,result.endReason||null,release,result.buildHash||null,JSON.stringify(result),new Date(room.created).toISOString(),timestamp);
      this.db.prepare('INSERT INTO match_statistics(match_id,summary_json,timeline_json,created_at) VALUES(?,?,?,?)').run(id,JSON.stringify({teamScores:result.teamScores,players:result.players,telemetry:result.telemetry}),JSON.stringify(result.telemetry?.timeline||[]),timestamp);
      this.log(JSON.stringify({event:'MATCH_COMPLETED',matchId:id,externalId,seasonId,matchType,rankedStatus,winner:result.winner}));
      if(rankedStatus==='unranked'||!participants.length){this.db.prepare("UPDATE matches SET rank_processing_status='skipped' WHERE id=?").run(id);return {persisted:true,matchId:id,ranked:false};}
      return {persisted:true,matchId:id,ranked:true,...this.ranking.processMatch({matchId:id,seasonId,result,participants,rankedStatus},{transaction:false})};
    });}catch(error){this.log(JSON.stringify({event:'RANK_PROCESSING_FAILED',matchId:id,message:error.message}));throw error;}
  }
  playerForUser(userId){return this.db.prepare('SELECT * FROM players WHERE user_id=?').get(userId);}
  profile(userId,{debug=false}={}){const player=this.playerForUser(userId);if(!player)return null;const user=this.db.prepare('SELECT id,username,email,display_name,avatar,region,created_at FROM users WHERE id=?').get(userId),rank=this.db.prepare('SELECT * FROM player_ranks WHERE player_id=? AND season_id=?').get(player.id,RANK_CONFIG.seasonId)||{rating:RANK_CONFIG.initialRating,mmr:RANK_CONFIG.initialMmr,rank_tier:tierForRating(RANK_CONFIG.initialRating).key,wins:0,losses:0,games_played:0,current_win_streak:0,current_loss_streak:0,peak_rating:RANK_CONFIG.initialRating},stats=this.db.prepare('SELECT * FROM player_statistics WHERE player_id=?').get(player.id)||{},achievements=this.db.prepare('SELECT a.key,a.name,a.description,pa.unlocked_at FROM player_achievements pa JOIN achievements a ON a.id=pa.achievement_id WHERE pa.player_id=? ORDER BY pa.unlocked_at DESC').all(player.id);const progress=rankProgress(rank.rating);return {user:{id:user.id,username:user.username,email:user.email,displayName:user.display_name,avatar:user.avatar,region:user.region,createdAt:user.created_at},rank:{rating:rank.rating,...(debug?{mmr:Math.round(rank.mmr)}:{}),tier:progress.tier,nextTier:progress.next,progress:progress.progress,wins:rank.wins,losses:rank.losses,gamesPlayed:rank.games_played,winRate:rank.games_played?rank.wins/rank.games_played:0,currentWinStreak:rank.current_win_streak,currentLossStreak:rank.current_loss_streak,peakRating:rank.peak_rating},statistics:stats,achievements};}
  publicProfile(playerId,{page=1,pageSize=10}={}){
    const player=this.db.prepare(`SELECT p.id,p.user_id,p.bot_id,p.display_name,p.player_type,p.strategy,p.version,p.faction,p.created_at,u.username,u.avatar,u.region,u.created_at user_created_at
      FROM players p LEFT JOIN users u ON u.id=p.user_id WHERE p.id=?`).get(playerId);
    if(!player)return null;
    page=positiveInt(page,1,100000);pageSize=positiveInt(pageSize,10,20);
    const rank=this.db.prepare('SELECT * FROM player_ranks WHERE player_id=? AND season_id=?').get(player.id,RANK_CONFIG.seasonId)||{rating:RANK_CONFIG.initialRating,rank_tier:tierForRating(RANK_CONFIG.initialRating).key,wins:0,losses:0,games_played:0,current_win_streak:0,current_loss_streak:0,peak_rating:RANK_CONFIG.initialRating};
    const progress=rankProgress(rank.rating),statistics=this.db.prepare('SELECT * FROM player_statistics WHERE player_id=?').get(player.id)||{},achievements=this.db.prepare('SELECT a.key,a.name,a.description,pa.unlocked_at FROM player_achievements pa JOIN achievements a ON a.id=pa.achievement_id WHERE pa.player_id=? ORDER BY pa.unlocked_at DESC').all(player.id),total=this.db.prepare('SELECT COUNT(*) total FROM match_players WHERE player_id=?').get(player.id).total;
    const matches=this.db.prepare(`SELECT m.id,m.match_type,m.ranked_status,m.winner,m.duration,m.completed_at,mp.role,mp.won,mp.rating_before,mp.rating_after,mp.rating_delta,
      (SELECT GROUP_CONCAT(p2.display_name, ', ') FROM match_players mp2 JOIN players p2 ON p2.id=mp2.player_id WHERE mp2.match_id=m.id AND mp2.player_id<>mp.player_id) opponents
      FROM match_players mp JOIN matches m ON m.id=mp.match_id WHERE mp.player_id=? ORDER BY m.completed_at DESC LIMIT ? OFFSET ?`).all(player.id,pageSize,(page-1)*pageSize);
    return {player:{id:player.id,displayName:player.display_name,playerType:player.player_type,username:player.username||null,avatar:player.avatar||null,region:player.region||null,botId:player.bot_id||null,strategy:player.strategy||null,version:player.version||null,faction:player.faction||null,createdAt:player.user_created_at||player.created_at},rank:{rating:rank.rating,tier:progress.tier,nextTier:progress.next,progress:progress.progress,wins:rank.wins,losses:rank.losses,gamesPlayed:rank.games_played,winRate:rank.games_played?rank.wins/rank.games_played:0,currentWinStreak:rank.current_win_streak,currentLossStreak:rank.current_loss_streak,peakRating:rank.peak_rating},statistics,achievements,history:{items:matches,page,pageSize,total}};
  }
  history(userId,{page=1,pageSize=20,role='all',result='all',matchType='all'}={}){const player=this.playerForUser(userId);if(!player)return {items:[],page,total:0,filters:{role,result,matchType}};page=positiveInt(page,1,100000);pageSize=positiveInt(pageSize,20,50);const clauses=['mp.player_id=?'],params=[player.id];if(['troll','elf'].includes(role)){clauses.push('mp.role=?');params.push(role);}if(result==='victory'){clauses.push('mp.won=1');}else if(result==='defeat'){clauses.push('mp.won=0');}if(['pvp','bots','custom','developer'].includes(matchType)){clauses.push('m.match_type=?');params.push(matchType);}const where=clauses.join(' AND '),total=this.db.prepare(`SELECT COUNT(*) total FROM match_players mp JOIN matches m ON m.id=mp.match_id WHERE ${where}`).get(...params).total,rows=this.db.prepare(`SELECT m.id,m.match_type,m.ranked_status,m.winner,m.duration,m.completed_at,m.seed,mp.role,mp.won,mp.rating_before,mp.rating_after,mp.rating_delta,mp.stats_json,mp.performance_json,(SELECT GROUP_CONCAT(p2.display_name, ', ') FROM match_players mp2 JOIN players p2 ON p2.id=mp2.player_id WHERE mp2.match_id=m.id AND mp2.player_id<>mp.player_id) opponents FROM match_players mp JOIN matches m ON m.id=mp.match_id WHERE ${where} ORDER BY m.completed_at DESC LIMIT ? OFFSET ?`).all(...params,pageSize,(page-1)*pageSize);return {items:rows.map(row=>({...row,stats:parse(row.stats_json),performance:parse(row.performance_json),stats_json:undefined,performance_json:undefined})),page,pageSize,total,filters:{role:['troll','elf'].includes(role)?role:'all',result:['victory','defeat'].includes(result)?result:'all',matchType:['pvp','bots','custom','developer'].includes(matchType)?matchType:'all'}};}
  matchDetails(matchId,userId){const match=this.db.prepare('SELECT * FROM matches WHERE id=?').get(matchId);if(!match)return null;const viewer=this.playerForUser(userId);if(!viewer||!this.db.prepare('SELECT 1 FROM match_players WHERE match_id=? AND player_id=?').get(matchId,viewer.id))return null;const players=this.db.prepare('SELECT mp.*,p.display_name,p.player_type,p.bot_id FROM match_players mp JOIN players p ON p.id=mp.player_id WHERE mp.match_id=? ORDER BY mp.won DESC,mp.rating_delta DESC').all(matchId).map(row=>({...row,stats:parse(row.stats_json),performance:parse(row.performance_json),stats_json:undefined,performance_json:undefined})),stats=this.db.prepare('SELECT * FROM match_statistics WHERE match_id=?').get(matchId);return {...match,result:parse(match.result_json),result_json:undefined,players,timeline:parse(stats?.timeline_json||'[]')};}
  ranked(userId,{debug=false}={}){const profile=this.profile(userId,{debug}),player=this.playerForUser(userId);if(!profile||!player)return null;const history=this.db.prepare('SELECT old_rating,new_rating,rating_delta,created_at,match_id FROM rank_history WHERE player_id=? AND season_id=? ORDER BY created_at ASC LIMIT 200').all(player.id,RANK_CONFIG.seasonId);return {...profile.rank,history,season:{id:RANK_CONFIG.seasonId,name:'Temporada 0 — Desenvolvimento'}};}
  seasons(){return this.db.prepare('SELECT id,name,kind,starts_at,ends_at,active FROM seasons ORDER BY starts_at DESC').all();}
  leaderboard({page=1,pageSize=25,role='overall',players='all',season=RANK_CONFIG.seasonId}={}){
    page=positiveInt(page,1,100000);pageSize=positiveInt(pageSize,25,50);const allTime=season==='all',clauses=[],params=[];
    if(!allTime){clauses.push('r.season_id=?');params.push(season);}
    if(players==='humans')clauses.push("p.player_type='human'");else if(players==='bots')clauses.push("p.player_type='bot'");
    if(['troll','elf'].includes(role)){clauses.push('EXISTS(SELECT 1 FROM match_players mp WHERE mp.player_id=p.id AND mp.role=?)');params.push(role);}
    const where=clauses.length?'WHERE '+clauses.join(' AND '):'',group=allTime?'GROUP BY p.id':'',total=this.db.prepare(`SELECT COUNT(*) total FROM (SELECT p.id FROM player_ranks r JOIN players p ON p.id=r.player_id ${where} ${group})`).get(...params).total;
    const fields=allTime?'MAX(r.rating) rating,SUM(r.wins) wins,SUM(r.losses) losses,SUM(r.games_played) games_played,MAX(r.peak_rating) peak_rating': 'r.rating,r.wins,r.losses,r.games_played,r.peak_rating';
    const rows=this.db.prepare(`SELECT p.id,p.display_name,p.player_type,p.bot_id,p.strategy,p.version,${fields} FROM player_ranks r JOIN players p ON p.id=r.player_id ${where} ${group} ORDER BY rating DESC,games_played DESC,p.display_name ASC LIMIT ? OFFSET ?`).all(...params,pageSize,(page-1)*pageSize);
    return {items:rows.map((row,index)=>({...row,rank_tier:tierForRating(row.rating).key,position:(page-1)*pageSize+index+1,winRate:row.games_played?row.wins/row.games_played:0})),page,pageSize,total,season,role,players,seasons:this.seasons()};
  }
  debugSummary(){if(!this.devMode)return null;const matches=this.db.prepare("SELECT COUNT(*) games,AVG(duration) average_duration,SUM(CASE WHEN winner='troll' THEN 1 ELSE 0 END) troll_wins,SUM(CASE WHEN winner='elves' THEN 1 ELSE 0 END) elf_wins FROM matches WHERE ranked_status='simulated_ranked'").get(),bots=this.db.prepare("SELECT p.id,p.display_name,p.bot_id,p.strategy,p.version,p.faction,r.rating,r.peak_rating,r.wins,r.losses,r.games_played FROM player_ranks r JOIN players p ON p.id=r.player_id WHERE p.player_type='bot' AND r.season_id=? ORDER BY r.rating DESC,r.games_played DESC").all(RANK_CONFIG.seasonId).map(row=>({...row,winRate:row.games_played?row.wins/row.games_played:0,rankTier:tierForRating(row.rating).key})),roleRatings=this.db.prepare("SELECT mp.role,AVG(pr.rating) average_rating FROM match_players mp JOIN player_ranks pr ON pr.player_id=mp.player_id AND pr.season_id=? GROUP BY mp.role").all(RANK_CONFIG.seasonId);return {...matches,trollWinRate:matches.games?matches.troll_wins/matches.games:0,elfWinRate:matches.games?matches.elf_wins/matches.games:0,averageRatingByRole:Object.fromEntries(roleRatings.map(row=>[row.role,Math.round(row.average_rating)])),bots,highestRatedBot:bots[0]||null,lowestRatedBot:bots.at(-1)||null};}
}
